# Site Metadata
title = 'Thielci'
baseURL = 'https://thielci.org'
relativeURLs = true
canonifyURLs = false
theme = 'hugo-theme-thielci'

# Default Language Configuration
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

# Menus and SEO
sectionPagesMenu = 'main'
enableRobotsTXT = true

# Pagination
[pagination]
pagerSize = 8 # Set low for demo; increase for production.

# Sitemap
[sitemap]
changefreq = 'monthly'
priority = 0.5
filename = 'sitemap.xml'

# Languages Configuration
[languages]
[languages.en]
disabled = false
languageCode = 'en-US'
languageDirection = 'ltr'
title = 'Thielci'
weight = 1
[languages.en.params.ananke.social.rss]
profilelink = '/en/posts/index.xml'

[languages.tr]
disabled = false
languageCode = 'tr-TR'
languageDirection = 'ltr'
title = 'Thielci'
weight = 2
[languages.tr.params.ananke.social.rss]
profilelink = '/tr/posts/index.xml'

# Site Parameters
[params]
text_color = ''
author = ''
favicon = ''
site_logo = ''
description = ''

# Design Options
background_color_class = 'bg-black' # From Tachyons color themes.
featured_image_class = 'cover bg-top' # Tachyons fitting/alignment styles.
cover_dimming_class = 'bg-black-60' # Tachyons dimming class.
recent_posts_number = 8
custom_css = ['toc_styles_override.css'] # CSS Overrides.

# Ananke-Specific Social Follow Links
[params.ananke.social.follow]
new_windows_icon = true
networks = [
  'rss'
]

# Permalinks
[permalinks]
posts = '/:sections/:slug/'

# Taxonomies
[taxonomies]
tag = 'tags'
